---

  # - name: cp artifact tar to ec2
  #   copy:
  #     src: ~/project/artifact.tar.gz
  #     dest: ~/

  # - name: install tar 
  #   become: yes
  #   apt:
  #     name: tar
  #     state: present

#   - name: mkdir backend folder
#     become: yes
#     shell: "{{ item }}"
#     with_items:
#       - mkdir ~/backend
#       - tar -xvzf ~/artifact.tar.gz -C ~/backend
#       - npm install
# #      - pm2 stop default
#       - pm2 start npm -- start

  - name: extract backend artifact
    become: yes
    command: "{{ item }}"
    with_items:
      - mkdir backend
      - tar -xvzf artifact.tar.gz -C backend
      - npm install
      - pm2 start npm -- start