---

  - name: cp artifact tar to ec2
    copy:
      src: ~/project/artifact.tar.gz
      dest: ~/

  - name: install tar 
    become: yes
    apt:
      name: tar
      state: present

  - name: extract backend artifact
    become: yes
    command: "{{ item }}"
    with_items:
      - mkdir backend
      - tar -xvzf artifact.tar.gz -C backend
      - cd backend
      - npm install
      - pm2 start npm -- start