---

  - name: cp artifact tar to ec2
    copy:
      src: ~/project/artifact.tar.gz
      dest: ~/

  - name: install tar 
    become: yes
    apt:
      name: tar
      state: present

  - name: extract backend artifact
    become: yes
    shell: |
      tar -xvzf ~/artifact.tar.gz
      npm install
      pm2 stop default
      pm2 start npm -- start